// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/17/2024, 4:07:07 PM
const configMerger = require("/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/plugins/**/*.{js,ts,mjs}","/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/composables/**/*.{js,ts,mjs}","/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/utils/**/*.{js,ts,mjs}","/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "/Users/diedegysens/Desktop/2BA/atelier bram/portfolio/PortfolioDiede/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
